#!/bin/bash

#SBATCH --mail-user=jjhale@umich.edu
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --export=ALL
#SBATCH --partition=standard
#SBATCH --account=esnitkin1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=50g
#SBATCH --time=48:00:00

module load singularity
#singularity exec panaroo_latest_10-16-24.sif panaroo -i sra_t60_prokka_gff/*.gff -o sra_t60_out/ --clean-mode moderate --remove-invalid-genes
#singularity exec --bind ./panaroo_data/:/opt/conda/lib/python3.9/site-packages/panaroo/ panaroo_1-5-1.sif panaroo -i sra_t60_prokka_gff/*.gff -o sra_t60_out/ --clean-mode moderate --remove-invalid-genes
#singularity exec ../panaroo/panaroo_1-5-1.sif panaroo -i 040825_shortread/prokka_gff_nodup/*.gff -o 040825_shortread/panaroo_out_v1/ --clean-mode moderate --remove-invalid-genes

#singularity exec ../panaroo/panaroo_1-5-1.sif panaroo -i 043025_shortread/prokka_gff_nodup/*.gff -o 043025_shortread/panaroo_out_v2/ --clean-mode moderate --remove-invalid-genes -a core

#singularity exec ../panaroo/panaroo_1-5-1.sif panaroo -i 060525_shortread/prokka_gff_nodup/*.gff -o 060525_shortread/panaroo_out_v1/ --clean-mode moderate --remove-invalid-genes --merge_paralogs

# output msa files
#singularity exec ../panaroo/panaroo_1-5-1.sif panaroo-msa --out_dir 060525_shortread/panaroo_out_v1/ --threads 8 --alignment pan --verbose


# run panaroo on MDHHS samples
# (make sure to use the biopython conda env for gffutils first)
#python3.12 panaroo_scripts/convert_wrapper.py --input 082625_mdhhs_quickbatch
#singularity exec panaroo_1-5-1.sif panaroo -i 082625_mdhhs_quickbatch/prokka_gff_nodup/*.gff -o 082625_mdhhs_quickbatch/panaroo_out_v1/ --clean-mode moderate --remove-invalid-genes --merge_paralogs --threads 8
#singularity exec panaroo_1-5-1.sif panaroo-msa --out_dir 082625_mdhhs_quickbatch/panaroo_out_v1/ --threads 8 --alignment core --verbose

# run panaroo on the new dataset of 1500 genomes
#singularity exec panaroo_1-5-1.sif panaroo -i 092525_pangenome_results/prokka_gff/*.gff -o 092525_pangenome_results/panaroo_out_v1 --clean-mode moderate --remove-invalid-genes --merge_paralogs --threads 16
# output msa files for this run
#singularity exec panaroo_1-5-1.sif panaroo-msa --out_dir 092525_pangenome_results/panaroo_out_v1/ --threads 16 --alignment pan --verbose

# run panaroo on the subset of 700 genomes, using the intron-spliced gff files
#singularity exec panaroo_1-5-1.sif panaroo -i 092525_pangenome_results/prokka_gff_spliceIntrons/*.gff \
#-o 092525_pangenome_results/panaroo_out_v2_spliceIntrons/ --clean-mode moderate --remove-invalid-genes --merge_paralogs --threads 16

# run panaroo on the subset of 700 genomes, using the intron-removed gff files
#singularity exec panaroo_1-5-1.sif panaroo -i 092525_pangenome_results/prokka_gff_removeIntrons/*.gff \
#-o 092525_pangenome_results/panaroo_out_v2_removeIntrons/ --clean-mode moderate --remove-invalid-genes --merge_paralogs --threads 16

# output msa files for the intron-spliced run of panaroo
#singularity exec panaroo_1-5-1.sif panaroo-msa --out_dir 092525_pangenome_results/panaroo_out_v2_spliceIntrons/ --threads 8 --alignment pan --verbose



# run panaroo on the dataset that includes haemuli outgroups
# singularity exec panaroo_1-5-1.sif panaroo -i 092525_pangenome_results/outgroup_data/prokka_gff_spliceIntrons/*.gff \
# -o 092525_pangenome_results/outgroup_data/panaroo_out_v3_spliceIntrons_outgroups/ --clean-mode moderate --remove-invalid-genes --merge_paralogs --threads 8

# output msa files for the outgroup intron-spliced run of panaroo
# singularity exec panaroo_1-5-1.sif panaroo-msa --out_dir 092525_pangenome_results/outgroup_data/panaroo_out_v3_spliceIntrons_outgroups/ --threads 8 --alignment pan --verbose


# have panaroo output the gff files with refound genes for the intron-spliced run without the outgroups
# use panaroo 1.6.0 for this, since it fixes an apparent issue with gff incompatability
singularity exec panaroo_1-6-0.sif panaroo-generate-gffs -i 092525_pangenome_results/prokka_gff_spliceIntrons/*.gff \
-o 092525_pangenome_results/panaroo_out_v2_spliceIntrons/ --threads 8 -f prokka --verbose



