#!/bin/bash

#SBATCH --mail-user=jjhale@umich.edu
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --export=ALL
#SBATCH --partition=standard
#SBATCH --account=esnitkin1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=30g
#SBATCH --time=03:00:00

# gffutils and biopython required

# prepare panaroo inputs
# python panaroo_scripts/convert_wrapper.py \
#     --assemblies /nfs/turbo/umms-esnitkin/Project_Cauris/Sequence_data/assembly/illumina/funannotate/ \
#     --additional-assemblies /nfs/turbo/umms-esnitkin/Project_Cauris/Sequence_data/assembly/hybrid/funannotate/ \
#     --output 092525_pangenome_results --skip-copy

# prepare orthofinder inputs
# python panaroo_scripts/create_ortho_commands.py -i 092525_pangenome_results/orthofinder_commands/ortho_commands_stdout.txt \
#     -o 092525_pangenome_results/orthofinder_commands/ortho_commands_array.txt


# prepare panaroo inputs, splicing all cds features that contain introns
#python panaroo_scripts/convert_wrapper_splice_introns.py --output 092525_pangenome_results --skip-copy --introns splice

# prepare panaroo inputs, deleting all cds features that contain introns
#python panaroo_scripts/convert_wrapper_splice_introns.py --output 092525_pangenome_results --skip-copy --introns remove
