#!/bin/bash

#SBATCH --mail-user=jjhale@umich.edu
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --export=ALL
#SBATCH --partition=largemem
#SBATCH --account=esnitkin1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=32
#SBATCH --mem=500g
#SBATCH --time=48:00:00

#module load singularity
#singularity exec orthofinder_latest_10-10-24.sif orthofinder -f test60/ -S diamond_ultra_sens -t 16
#singularity exec orthofinder_latest_10-10-24.sif orthofinder -f test60/ -t 16
#singularity exec ../orthofinder/orthofinder_latest_10-10-24.sif orthofinder -f 043025_shortread/protein_fasta_nodup/ -t 16

# use the orthofinder conda env for orthofinder v3
#orthofinder -f 092525_pangenome_results/original_protein_fasta/ -t 16 -a 16 -o 092525_pangenome_results/orthofinder_out_v1/ -op

# remove the previous run in progress
#rm -r 092525_pangenome_results/orthofinder_out_v1/Results_Sep29/WorkingDirectory/*

# create a new directory containing only the 700 isolates
#python panaroo_scripts/filter_fastas.py --input 092525_pangenome_results/original_protein_fasta/ \
#--filter_file subset700_data/master_qc_file_PassOnly_v2.csv --output 092525_pangenome_results/subset700_original_protein_fasta/

# run orthofinder on this new directory, printing only the commands to run
#orthofinder -f 092525_pangenome_results/subset700_original_protein_fasta/ -t 16 -a 16 -o 092525_pangenome_results/orthofinder_out_subset700_v2/ -op

# copy just the orthofinder commands to a separate file (run this locally)
#python panaroo_scripts/create_ortho_commands.py --input 092525_pangenome_results/orthofinder_commands/700subset/ortho_commands_stout.txt \
#--output 092525_pangenome_results/orthofinder_commands/700subset/ortho_commands_array.txt

# split this text file into individual batches of 1000 commands each (run this locally)
# mkdir -p 092525_pangenome_results/orthofinder_commands/700subset/split_commands/

# split 092525_pangenome_results/orthofinder_commands/700subset/ortho_commands_array.txt \
# 092525_pangenome_results/orthofinder_commands/700subset/split_commands/split_ortho_command_ \
# --lines=1000 -d --additional-suffix=.txt -a 3

# run orthofinder using the pre-computed DIAMOND results
orthofinder -t 32 -a 32 -b 092525_pangenome_results/orthofinder_out_subset700_v2/Results_Oct04/WorkingDirectory/
