#!/bin/bash

#SBATCH --mail-user=jjhale@umich.edu
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --export=ALL
#SBATCH --partition=standard
#SBATCH --account=esnitkin1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=24
#SBATCH --mem=100g
#SBATCH --time=48:00:00

module load singularity

# initial run
#singularity exec iqtree2_2-4-0.sif iqtree2 -s /nfs/turbo/umms-esnitkin/Project_Cauris/Analysis/2024_Pipeline_testing/2025-05-06_pvo/043025_shortread/panaroo_out_v1/aligned_gene_sequences_rename/ --seqtype DNA --mem 15G -T AUTO

# iqtree run on the first ~350 isolates
#singularity exec iqtree2_2-4-0.sif iqtree2 -s panaroo_out_v1/aligned_gene_sequences_rename_v2/ --seqtype DNA --mem 15G -T AUTO --safe -m GTR+F+I+R8 -B 1000

# iqtree run on the initial set of MDHHS isolates
# singularity exec iqtree2_2-4-0.sif iqtree2 -s 082625_mdhhs_quickbatch_panaroo/renamed_aligned_gene_sequences_all_5500/ --seqtype DNA --mem 15G -T AUTO --safe -m GTR+F+I+R8 -B 1000


# run iqtree on the haemuli filtered msa files, not specifying model or bootstrap
# this will likely not complete in time, but should hopefully generate a model at least
# singularity exec iqtree2_2-4-0.sif iqtree2 -s 092525_pangenome_results/iqtree_v1/iqtree_msa_files_haemuli/ \
# --seqtype DNA --mem 100G -T AUTO --safe -o CanHae,CanDuoHae,CanPseudoHae

# re-run iqtree on only the single-copy core gene msas from the haemuli panaroo run
singularity exec iqtree2_2-4-0.sif iqtree2 -s 092525_pangenome_results/iqtree_v2/iqtree_msa_files_haemuli/ \
--seqtype DNA --mem 100G -T AUTO --safe -o CanHae,CanDuoHae,CanPseudoHae

