#!/bin/bash

#SBATCH --mail-user=jjhale@umich.edu
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --export=ALL
#SBATCH --partition=standard
#SBATCH --account=esnitkin1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=15g
#SBATCH --time=10:00:00

# biopython conda env needed

module load Bioinformatics mafft/7.310

python iqtree_scripts/prepare_iqtree_msa.py --input 092525_pangenome_results/panaroo_out_v2_spliceIntrons/aligned_gene_sequences/ \
--output 092525_pangenome_results/iqtree_v1/iqtree_msa_files_c_albicans/ \
--qc_file 092525_pangenome_results/subset700_data/master_qc_file_PassOnly_v2.csv \
--outgroup_gff /nfs/turbo/umms-esnitkin/Project_Cauris/Analysis/2024_Pipeline_testing/2025-10-23_candida_outgroups/CanAlb_SC5314_v3.0/genomic.gff \
--outgroup_fasta /nfs/turbo/umms-esnitkin/Project_Cauris/Analysis/2024_Pipeline_testing/2025-10-23_candida_outgroups/CanAlb_SC5314_v3.0/GCA_000182965.3_ASM18296v3_genomic.fna \
--ortholog /nfs/turbo/umms-esnitkin/Project_Cauris/Analysis/2024_Pipeline_testing/2025-10-23_candida_outgroups/CanAlb_SC5314_v3.0/orthologs/candida_albicans_orthologs_of_families.tsv \
--outgroup_name SC5314


